import GRDB

/// Owns the SQLite connection and schema migration. Construct via
/// `open(atPath:)` (real file, for the app) or `openInMemory()` (tests).
public final class IMDatabase {
    public let dbQueue: DatabaseQueue

    private init(dbQueue: DatabaseQueue) throws {
        self.dbQueue = dbQueue
        try Self.migrator.migrate(dbQueue)
    }

    public static func open(atPath path: String) throws -> IMDatabase {
        try IMDatabase(dbQueue: DatabaseQueue(path: path))
    }

    public static func openInMemory() throws -> IMDatabase {
        try IMDatabase(dbQueue: DatabaseQueue())
    }

    private static var migrator: DatabaseMigrator {
        var migrator = DatabaseMigrator()
        migrator.registerMigration("v1_createSchema") { db in
            try db.create(table: "message") { t in
                t.autoIncrementedPrimaryKey("id")
                t.column("localMessageId", .integer).notNull()
                t.column("messageUid", .integer).notNull().defaults(to: 0)
                t.column("conversationType", .integer).notNull()
                t.column("target", .text).notNull()
                t.column("line", .integer).notNull().defaults(to: 0)
                t.column("from", .text).notNull()
                t.column("contentType", .integer).notNull()
                t.column("textContent", .text)
                t.column("searchableContent", .text)
                t.column("mediaRemoteURL", .text)
                t.column("mediaLocalPath", .text)
                t.column("mediaThumbnail", .blob)
                t.column("timestamp", .integer).notNull()
                t.column("status", .integer).notNull()
                t.column("direction", .integer).notNull()
            }
            try db.create(
                index: "message_on_conversation_timestamp",
                on: "message",
                columns: ["conversationType", "target", "line", "timestamp"]
            )
            // Partial unique index, scoped to my own sent messages only.
            // local_message_id is generated by `MessageShardingUtil.generateId()`
            // on Android (timestamp(43 bits since 2018-01-01) + nodeId(6) +
            // rotating counter(15), Snowflake-style) — quasi-globally-unique by
            // construction for messages *I* send, which is the only case this
            // column's dedup purpose (matching my own pending sends against
            // server acks/redeliveries after reconnect) applies to. It must
            // NOT be globally unique across all rows: a message I *receive*
            // may carry a `local_message_id` chosen by a completely different
            // sender's device, and there is no cross-device coordination
            // preventing that value from coinciding with one I've used myself
            // — a blanket UNIQUE constraint would risk rejecting a legitimate
            // received message because of an unrelated sender's ID.
            try db.create(
                index: "message_on_local_message_id_for_sent",
                on: "message",
                columns: ["localMessageId"],
                options: .unique,
                condition: Column("direction") == MessageDirection.send.rawValue
            )

            try db.create(table: "conversation") { t in
                t.column("conversationType", .integer).notNull()
                t.column("target", .text).notNull()
                t.column("line", .integer).notNull().defaults(to: 0)
                t.column("lastMessageUid", .integer)
                t.column("timestamp", .integer).notNull().defaults(to: 0)
                t.column("unreadCount", .integer).notNull().defaults(to: 0)
                t.column("isTop", .boolean).notNull().defaults(to: false)
                t.column("isMuted", .boolean).notNull().defaults(to: false)
                t.column("draft", .text)
                t.primaryKey(["conversationType", "target", "line"])
            }

            try db.create(table: "user") { t in
                t.column("uid", .text).notNull().primaryKey()
                t.column("name", .text)
                t.column("displayName", .text)
                t.column("portrait", .text)
                t.column("mobile", .text)
                t.column("gender", .integer).notNull().defaults(to: 0)
                t.column("updateDt", .integer).notNull().defaults(to: 0)
            }

            try db.create(table: "syncState") { t in
                t.column("id", .integer).notNull().primaryKey()
                t.column("msgHead", .integer).notNull().defaults(to: 0)
                t.column("friendHead", .integer).notNull().defaults(to: 0)
                t.column("friendRequestHead", .integer).notNull().defaults(to: 0)
                t.column("settingHead", .integer).notNull().defaults(to: 0)
            }
        }
        migrator.registerMigration("v2_addUserIsFriend") { db in
            try db.alter(table: "user") { t in
                t.add(column: "isFriend", .boolean).notNull().defaults(to: false)
            }
        }
        migrator.registerMigration("v3_addFriendRequestTable") { db in
            try db.create(table: "friendRequest") { t in
                t.column("fromUid", .text).notNull()
                t.column("toUid", .text).notNull()
                t.column("reason", .text).notNull().defaults(to: "")
                t.column("status", .integer).notNull().defaults(to: 0)
                t.column("updateDt", .integer).notNull().defaults(to: 0)
                t.column("fromReadStatus", .boolean).notNull().defaults(to: false)
                t.column("toReadStatus", .boolean).notNull().defaults(to: false)
                t.primaryKey(["fromUid", "toUid"])
            }
        }
        migrator.registerMigration("v4_addGroupSupport") { db in
            try db.create(table: "groupInfo") { t in
                t.column("groupId", .text).notNull().primaryKey()
                t.column("name", .text).notNull()
                t.column("portrait", .text)
                t.column("owner", .text)
                t.column("groupType", .integer).notNull().defaults(to: 0)
                t.column("memberCount", .integer).notNull().defaults(to: 0)
                t.column("updateDt", .integer).notNull().defaults(to: 0)
                t.column("memberUpdateDt", .integer).notNull().defaults(to: 0)
            }
            try db.create(table: "groupMember") { t in
                t.column("groupId", .text).notNull()
                t.column("memberId", .text).notNull()
                t.column("memberType", .integer).notNull().defaults(to: 0)
                t.column("updateDt", .integer).notNull().defaults(to: 0)
                t.primaryKey(["groupId", "memberId"])
            }
            try db.alter(table: "message") { t in
                t.add(column: "mentionedType", .integer).notNull().defaults(to: 0)
                t.add(column: "mentionedTargetsRaw", .text)
                t.add(column: "groupNotificationOperator", .text)
                t.add(column: "groupNotificationMembersRaw", .text)
                t.add(column: "groupNotificationValue", .text)
            }
            try db.alter(table: "conversation") { t in
                t.add(column: "unreadMentionCount", .integer).notNull().defaults(to: 0)
            }
        }
        migrator.registerMigration("v5_addCallRecord") { db in
            try db.alter(table: "message") { t in
                t.add(column: "callId", .text)
                t.add(column: "callTargetId", .text)
                t.add(column: "callAudioOnly", .boolean).notNull().defaults(to: false)
                t.add(column: "callStatus", .integer).notNull().defaults(to: 0)
                t.add(column: "callConnectTime", .integer).notNull().defaults(to: 0)
                t.add(column: "callEndTime", .integer).notNull().defaults(to: 0)
            }
        }
        return migrator
    }
}
