import XCTest
@testable import IMClient

final class WireCryptoTests: XCTestCase {
    // Default key bytes from AES.java's `aes_key` field, used when the
    // Java `AESDecrypt(data, "", false)` call site passes an empty userKey.
    let defaultKey = WireCrypto.defaultKey

    func test_defaultKey_matchesJavaSourceBytes() {
        XCTAssertEqual(defaultKey, [
            0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77,
            0x78, 0x79, 0x7A, 0x7B, 0x7C, 0x7D, 0x7E, 0x7F,
        ])
    }

    func test_keyFromSecret_matchesJavaConvertUserKey() {
        // Java: charAt(i) & 0xFF for the first 16 chars of the secret string.
        let key = WireCrypto.key(fromSecret: "mySecretKey12345extra")
        XCTAssertEqual(key, Data(hex: "6d795365637265744b65793132333435").map { $0 })
    }

    func test_decryptRaw_matchesRealJavaCiphertext_defaultKey() throws {
        // Generated by: Cipher.getInstance("AES/CBC/PKCS5Padding"), IV = key,
        // key = defaultKey, plaintext = "hello world12345" (exactly 16 bytes).
        let ciphertext = Data(hex: "521ff34210886dfb5be46fd4eaeb7a59dc3a6768c8ced7c8fa88740e0dadd210")
        let plaintext = try WireCrypto.decryptRaw(ciphertext, key: defaultKey)
        XCTAssertEqual(String(data: plaintext, encoding: .utf8), "hello world12345")
    }

    func test_encryptRaw_matchesRealJavaCiphertext_secretDerivedKey() throws {
        // Generated by the same Java Cipher call with key = convertUserKey("mySecretKey12345extra"), plaintext = "abc".
        let key = WireCrypto.key(fromSecret: "mySecretKey12345extra")
        let ciphertext = try WireCrypto.encryptRaw(Data("abc".utf8), key: key)
        XCTAssertEqual(ciphertext, Data(hex: "5fdea8d410f94872a17e8b03e4a1ecb2"))
    }

    func test_decryptRaw_secretDerivedKey_matchesJava() throws {
        let key = WireCrypto.key(fromSecret: "mySecretKey12345extra")
        let plaintext = try WireCrypto.decryptRaw(Data(hex: "5fdea8d410f94872a17e8b03e4a1ecb2"), key: key)
        XCTAssertEqual(plaintext, Data("abc".utf8))
    }

    func test_prependTimestampPrefix_topByteIsAlwaysZero_matchingJavaBug() {
        // AES.java computes byte3 as `(byte)((curhour & 0xFF) >> 24)`, which
        // masks to 8 bits *before* shifting right 24 — always zero. This is
        // a real bug in the original, faithfully preserved (the server's
        // decoder expects this exact layout, not a "corrected" one).
        let prefixed = WireCrypto.prependTimestampPrefix(Data(), hours: 0x01FF_FFFF)
        XCTAssertEqual(prefixed[3], 0)
    }

    func test_fullEncryptWithFixedTimestamp_matchesRealJavaCiphertext_defaultKey() throws {
        // Generated by a Java port of AES.AESEncrypt with curhour hardcoded to 12345
        // (instead of System.currentTimeMillis()-derived, for reproducibility),
        // plaintext = "cGFzc3dvcmQ=|mySecretKey12345|extra", key = defaultKey.
        let plaintext = Data("cGFzc3dvcmQ=|mySecretKey12345|extra".utf8)
        let prefixed = WireCrypto.prependTimestampPrefix(plaintext, hours: 12345)
        let ciphertext = try WireCrypto.encryptRaw(prefixed, key: defaultKey)
        XCTAssertEqual(ciphertext, Data(hex: "4055f48f2467148749d6218dbaa4f0b3719f48a15eeaf8f40c3173a4b2ee528cae47f5cd4b47f7291bd1fef1d48b2364"))
    }

    func test_fullEncryptWithFixedTimestamp_matchesRealJavaCiphertext_secretDerivedKey() throws {
        // Generated the same way with curhour=99999, key = convertUserKey("mySecretKey12345"),
        // plaintext = Base64.decode("cGFzc3dvcmQ=") (the raw bytes of "password").
        let key = WireCrypto.key(fromSecret: "mySecretKey12345")
        let plaintext = Data(base64Encoded: "cGFzc3dvcmQ=")!
        let prefixed = WireCrypto.prependTimestampPrefix(plaintext, hours: 99999)
        let ciphertext = try WireCrypto.encryptRaw(prefixed, key: key)
        XCTAssertEqual(ciphertext, Data(hex: "661592c1662aec485eaf20306393ee42"))
    }

    func test_fullEncryptThenFullDecrypt_roundTrips() throws {
        let plaintext = Data("round-trip-payload".utf8)
        let ciphertext = try WireCrypto.encrypt(plaintext, key: defaultKey)
        let decrypted = try WireCrypto.decrypt(ciphertext, key: defaultKey)
        XCTAssertEqual(decrypted, plaintext)
    }

    func test_stripTimestampPrefix_tooShortInputThrows() {
        XCTAssertThrowsError(try WireCrypto.stripTimestampPrefix(Data([0x01, 0x02]))) { error in
            XCTAssertEqual(error as? WireCrypto.Error, .payloadTooShortForTimestampPrefix)
        }
    }
}
